-- AlterTable
ALTER TABLE "user_topics" ALTER COLUMN "score" SET DEFAULT 50,
ALTER COLUMN "score" DROP DEFAULT,
ALTER COLUMN "score" TYPE INTEGER USING ROUND("score")::INTEGER,
ALTER COLUMN "score" SET DEFAULT 50;
